# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7de9b3eb2e07afa51ef7a5328923d491d422151a6f942fba1fa30ee9d18dd09894c75cd1d1ce64a2dbc358af97e0047f89f620ce48ad844dd633f77086531d26

test:
  secret_key_base: 60ffc0df13e188aa91939a0214a750c485def2c3dc08e37b5941226207c9de6a8ed59aebb3303956d89345b94a2a92f055c5bec6fd7fc09c10d71fb3a9f68849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
